#!/usr/bin/env bash
#
# render-docs.sh — regenerate the credentials table in README.md from the
# manifest in setup-env.sh, so the two cannot drift.
#
#   ./deploy/github/render-docs.sh          # rewrite the block
#   ./deploy/github/render-docs.sh --check  # fail if it is out of date (CI)
set -euo pipefail

HERE="$(cd "$(dirname "$0")" && pwd)"
README="$HERE/../../README.md"
BEGIN='<!-- BEGIN credentials (generated by deploy/github/render-docs.sh) -->'
END='<!-- END credentials -->'

table="$("$HERE/setup-env.sh" production --markdown)"
new="$(awk -v b="$BEGIN" -v e="$END" -v t="$table" '
  $0 == b { print; print t; skip = 1; next }
  $0 == e { skip = 0 }
  !skip   { print }
' "$README")"

grep -qF "$BEGIN" "$README" || { echo "marker missing from README.md"; exit 1; }

if [ "${1:-}" = "--check" ]; then
  diff -u <(cat "$README") <(printf '%s\n' "$new") >/dev/null && { echo "README credentials table is current"; exit 0; }
  echo "README credentials table is STALE — run ./deploy/github/render-docs.sh" >&2
  diff -u <(cat "$README") <(printf '%s\n' "$new") | head -30 >&2
  exit 1
fi

printf '%s\n' "$new" > "$README"
echo "README credentials table regenerated"
