// ESLint 10 flat config, replacing .eslintrc.cjs + .eslintignore (both formats
// were dropped). Same rule set as before: eslint:recommended,
// @typescript-eslint/recommended, svelte/recommended, prettier last so it wins
// on formatting.
import js from '@eslint/js';
import ts from 'typescript-eslint';
import svelte from 'eslint-plugin-svelte';
import prettier from 'eslint-config-prettier';
import globals from 'globals';
import svelteParser from 'svelte-eslint-parser';

export default ts.config(
	{
		// Replaces .eslintignore. Flat config has no separate ignore file.
		ignores: [
			'.svelte-kit/**',
			'build/**',
			'package/**',
			'coverage/**',
			'.wrangler/**',
			'static/**'
		]
	},
	js.configs.recommended,
	...ts.configs.recommended,
	...svelte.configs['flat/recommended'],
	prettier,
	...svelte.configs['flat/prettier'],
	{
		languageOptions: {
			globals: { ...globals.browser, ...globals.node }
		},
		rules: {
			// Rules that eslint-plugin-svelte 3 and ESLint 10 ADDED to their
			// recommended presets. Adopting them means changing application code —
			// 70 links to route through resolve(), 48 keyed each-blocks — which is a
			// refactor, not a dependency upgrade, so they are deferred rather than
			// smuggled in here.
			//
			// `eslint .` already failed on main with 205 errors (189 of them
			// no-explicit-any) and is not run by CI, which runs `npm run check`.
			// These three lines hold that number where it was instead of tripling
			// it, so the upgrade does not quietly make the lint baseline worse.
			'svelte/prefer-svelte-reactivity': 'off',
			'svelte/no-reactive-reassign': 'off',
			'no-useless-assignment': 'off'
		}
	},
	{
		files: ['**/*.svelte'],
		languageOptions: {
			parser: svelteParser,
			parserOptions: {
				// Type-aware parsing inside <script lang="ts">.
				parser: ts.parser,
				extraFileExtensions: ['.svelte']
			}
		},
		rules: {
			// typescript-eslint 8's no-unused-vars crashes on svelte-eslint-parser's
			// AST ("Cannot read properties of undefined (reading 'type')") because
			// template-only references have no declaration node it recognises.
			// Turned off rather than worked around: svelte-check already reports
			// unused variables in .svelte files, so nothing is lost.
			'@typescript-eslint/no-unused-vars': 'off'
		}
	},
	{
		// Generated by scripts/wrap-worker.mjs at build time; not source.
		files: ['scripts/**'],
		languageOptions: { globals: globals.node }
	}
);
