#!/usr/bin/env bash
#
# external-watch.sh — configure the outside-in monitoring: Better Stack watching
# the public endpoints, and a Better Stack heartbeat as the evaluator's
# dead-man's switch. Same shape as cloudflare/tunnel.sh — plain curl + jq,
# idempotent.
#
#   ./deploy/external-watch.sh production
#   ./deploy/external-watch.sh staging --remove   # tear this environment's down
#
# nabz cannot be its own only watcher: its dead-man's switch runs inside the
# evaluator and dies with it. These two services are independent of our infra
# and of our CI.
#
# One Better Stack account serves every environment, so everything created here is
# namespaced by env and never touches another's: monitors are matched on URL
# (which already differs per env) and carry the env in their title, and the
# heartbeat carries it in its name. The one exception is the outgoing webhooks,
# which Better Stack scopes to the account and not to monitors — see below.
#
# Credentials are shared across environments, so they belong in nabz-shared:
#   BETTERSTACK_API_TOKEN   Better Stack > Settings > API tokens
# Non-secret targets come from deploy/environments/<env>.vars.
set -euo pipefail

ENV_NAME="${1:-}"
MODE="${2:-upsert}"
[ -n "$ENV_NAME" ] || { echo "usage: $0 <production|staging> [--remove]" >&2; exit 1; }
case "$MODE" in upsert|--remove) ;; *) echo "usage: $0 <env> [--remove]" >&2; exit 1 ;; esac
case "$ENV_NAME" in prod) ENV_NAME=production ;; esac

HERE="$(cd "$(dirname "$0")" && pwd)"
die() { echo "error: $*" >&2; exit 1; }
command -v jq >/dev/null 2>&1 || die "missing jq"

# Generated by bootstrap-credentials into GitHub secrets, so it arrives in the
# environment rather than from Bitwarden. Keep it across the materialization.
_hdt="${HEALTH_DEBUG_TOKEN:-}"
eval "$("$HERE/bws-env.sh" "$ENV_NAME" --stdout)"
[ -n "$_hdt" ] && HEALTH_DEBUG_TOKEN="$_hdt"

# An environment that exists for a couple of hours has nothing worth watching:
# its monitors and heartbeat would be red the whole time it is not running, which
# trains you to ignore the alerts that matter. EXTERNAL_WATCH=off in the vars file
# opts an environment out entirely. --remove still works, so anything created
# before the opt-out can be cleaned up.
if [ "${EXTERNAL_WATCH:-on}" = off ] && [ "$MODE" != "--remove" ]; then
  echo "external monitoring is off for '$ENV_NAME' (EXTERNAL_WATCH=off in"
  echo "deploy/environments/${ENV_NAME}.vars). Nothing created."
  exit 0
fi
: "${WEB_URL:?WEB_URL missing from deploy/environments/${ENV_NAME}.vars}"
: "${BETTERSTACK_API_TOKEN:?BETTERSTACK_API_TOKEN is not in the ${ENV_NAME} Bitwarden project}"
# Only the PocketBase probe needs it, so a teardown must not demand it — a
# half-provisioned environment is exactly when you want to be able to clean up.
if [ "$MODE" != "--remove" ]; then
  : "${HEALTH_DEBUG_TOKEN:?HEALTH_DEBUG_TOKEN is not set. It is generated by the bootstrap-credentials workflow into GitHub secrets, not Bitwarden — run that for '$ENV_NAME' first, or export it here.}"
fi

CHECK_FREQUENCY="${CHECK_FREQUENCY:-180}"   # 3 min, comfortably inside the free tier
BS="https://uptime.betterstack.com/api/v2/monitors"
BS_WH="https://uptime.betterstack.com/api/v2/outgoing-webhooks"
BS_HB="https://uptime.betterstack.com/api/v2/heartbeats"

bs() { # METHOD PATH [json]
  local m="$1" p="$2" b="${3:-}" out
  if [ -n "$b" ]; then
    out="$(curl -sS -X "$m" "$BS$p" -H "Authorization: Bearer $BETTERSTACK_API_TOKEN" \
      -H 'Content-Type: application/json' -d "$b")"
  else
    out="$(curl -sS -X "$m" "$BS$p" -H "Authorization: Bearer $BETTERSTACK_API_TOKEN")"
  fi
  # A successful DELETE returns 204 with no body. Feeding that to jq fails, which
  # would report a completed deletion as an error and abort the rest of a teardown.
  [ -z "${out//[[:space:]]/}" ] && return 0
  jq -e 'has("errors") | not' >/dev/null 2>&1 <<<"$out" \
    || die "Better Stack $m $p: $out"
  echo "$out"
}

# Match on url, which is what actually identifies a monitor — renaming one in the
# dashboard must not make this create a duplicate.
existing="$(bs GET "?per_page=50")"
upsert_monitor() { # name url json-extra
  local name="$1" url="$2" extra="$3" id body
  id="$(jq -r --arg u "$url" '.data[] | select(.attributes.url == $u) | .id' <<<"$existing" | head -1)"
  body="$(jq -nc --arg n "$name" --arg u "$url" --argjson f "$CHECK_FREQUENCY" --argjson x "$extra" \
    '{pronounceable_name:$n, url:$u, check_frequency:$f, email:false, sms:false, call:false} + $x')"
  if [ -n "$id" ]; then
    bs PATCH "/$id" "$body" >/dev/null
    echo "   updated  $name"
  else
    bs POST "" "$body" >/dev/null
    echo "   created  $name"
  fi
}

# Every URL below starts with this environment's WEB_URL, and WEB_URL differs per
# environment, so it is both the namespace and the teardown filter.
if [ "$MODE" = "--remove" ]; then
  echo "==> Better Stack: removing monitors under ${WEB_URL}"
  n=0
  for id in $(jq -r --arg u "${WEB_URL%/}" \
      '.data[] | select((.attributes.url // "") | startswith($u)) | .id' <<<"$existing"); do
    bs DELETE "/$id" >/dev/null; n=$((n+1))
  done
  echo "   deleted $n"
  # Account-wide, so tearing down staging must not disarm production's alerting.
  if [ "$ENV_NAME" = production ]; then
    echo "==> Better Stack: removing the Telegram webhooks"
    whs="$(curl -sS "$BS_WH" -H "Authorization: Bearer $BETTERSTACK_API_TOKEN")"
    m=0
    for id in $(jq -r '.data[] | select((.attributes.name // "") | startswith("nabz telegram")) | .id' <<<"$whs"); do
      curl -sS -X DELETE "$BS_WH/$id" -H "Authorization: Bearer $BETTERSTACK_API_TOKEN" >/dev/null
      m=$((m+1))
    done
    echo "   deleted $m"
  else
    echo "==> Better Stack: leaving the Telegram webhooks (account-wide, production owns them)"
  fi

  echo "==> Better Stack: removing the ${ENV_NAME} heartbeat"
  hbs_all="$(curl -sS "$BS_HB" -H "Authorization: Bearer $BETTERSTACK_API_TOKEN")"
  n=0
  for hb_id in $(jq -r --arg e "(${ENV_NAME})" \
      '.data[] | select((.attributes.name // "") | endswith($e)) | .id' <<<"$hbs_all"); do
    curl -sS -X DELETE "$BS_HB/$hb_id" -H "Authorization: Bearer $BETTERSTACK_API_TOKEN" >/dev/null
    n=$((n+1))
  done
  echo "   deleted $n"
  exit 0
fi

echo "==> Better Stack (every ${CHECK_FREQUENCY}s)"
upsert_monitor "nabz site (${ENV_NAME})" "$WEB_URL" '{"monitor_type":"status"}'

# Public health tier: a 200 is not enough — the body has to say ok.
upsert_monitor "nabz health (${ENV_NAME})" "${WEB_URL%/}/api/health" \
  '{"monitor_type":"keyword","required_keyword":"\"status\":\"ok\""}'

# PocketBase is behind Access and 403s anything without a service token, so it is
# watched THROUGH the health endpoint's debug tier instead of directly.
# ?probe= is ignored by the endpoint and makes the URL unique, which matters
# because the upsert is keyed on URL — without it this monitor and the public one
# collide and each re-run overwrites the other.
upsert_monitor "nabz pocketbase (${ENV_NAME})" "${WEB_URL%/}/api/health?probe=pocketbase" \
  "$(jq -nc --arg h "Bearer $HEALTH_DEBUG_TOKEN" \
    '{monitor_type:"keyword", required_keyword:"\"name\":\"pocketbase\",\"status\":\"ok\"",
      request_headers:[{name:"Authorization", value:$h}]}')"

# --- Telegram, via Better Stack outgoing webhooks -----------------------------
# Better Stack has no Telegram integration, but it can POST an arbitrary body to
# an arbitrary URL, and Telegram's sendMessage is exactly that. The template
# variable syntax is undocumented, so rather than guess at interpolation this
# creates two webhooks with fixed text, split by the on_incident_* flags — a
# message that always says the right thing beats one with a broken placeholder.
# Outgoing webhooks are ACCOUNT-WIDE. There is no monitor, group or policy filter
# on them — only name, url, trigger and the on_incident_* flags. So a per-
# environment pair would both fire on every incident, one message claiming
# production and one claiming staging, whichever actually broke. That is worse
# than no alerting, so there is exactly one pair, owned by the production run, and
# the text names no environment because the template variable syntax to name the
# monitor is undocumented and cannot be verified from here (the Bot API returns
# incoming updates only, so what the bot SENDS is not readable back).
if [ -n "${NABZ_CHECK_TELEGRAM_BOT_TOKEN:-}" ] && [ "$ENV_NAME" != production ]; then
  echo "==> Telegram: skipped — the webhooks are account-wide and owned by production"
elif [ -n "${NABZ_CHECK_TELEGRAM_BOT_TOKEN:-}" ]; then
  echo "==> Telegram (via Better Stack outgoing webhooks, account-wide)"
  tg_api="https://api.telegram.org/bot${NABZ_CHECK_TELEGRAM_BOT_TOKEN}"
  chat="${NABZ_CHECK_TELEGRAM_CHAT_ID:-}"
  if [ -z "$chat" ]; then
    # Discoverable only after someone has messaged the bot; getUpdates is empty
    # until then, and Telegram drops updates after 24h.
    chat="$(curl -sS --max-time 10 "$tg_api/getUpdates" \
      | jq -r '[.result[]?.message.chat.id] | last // empty')"
  fi
  if [ -z "$chat" ]; then
    echo "   SKIPPED: no chat id. Send /start to the bot (or add it to your group),"
    echo "   then re-run — or set NABZ_CHECK_TELEGRAM_CHAT_ID in Bitwarden."
  else
    existing_wh="$(curl -sS "$BS_WH" -H "Authorization: Bearer $BETTERSTACK_API_TOKEN")"
    # The two webhooks need DISTINCT urls: an update that would leave two webhooks
    # sharing one url is dropped, silently and with a 200. Telegram ignores the
    # extra query param when the parameters come from a JSON body, so ?nabz=<slot>
    # makes each url unique — the same trick as ?probe= on the monitors.
    upsert_webhook() { # slot text on_started on_resolved
      local slot="$1" text="$2" started="$3" resolved="$4" name url id tid attrs got
      name="nabz telegram $slot"
      url="$tg_api/sendMessage?nabz=$slot"
      id="$(jq -r --arg n "$name" '.data[] | select(.attributes.name == $n) | .id' <<<"$existing_wh" | head -1)"
      attrs="$(jq -nc --arg n "$name" --arg u "$url" \
        --argjson st "$started" --argjson re "$resolved" \
        '{name:$n, url:$u, trigger_type:"incident_change",
          on_incident_started:$st, on_incident_resolved:$re,
          on_incident_acknowledged:false, on_incident_reopened:$st, on_incident_comment:false}')"
      if [ -n "$id" ]; then
        curl -sS -X PATCH "$BS_WH/$id" -H "Authorization: Bearer $BETTERSTACK_API_TOKEN" \
          -H 'Content-Type: application/json' -d "$attrs" >/dev/null
        # url, like the template, is only honoured in a request of its own. In a
        # combined PATCH it is accepted with a 200 and dropped — so after rotating
        # the bot token the webhooks keep posting to the dead one.
        curl -sS -X PATCH "$BS_WH/$id" -H "Authorization: Bearer $BETTERSTACK_API_TOKEN" \
          -H 'Content-Type: application/json' -d "$(jq -nc --arg u "$url" '{url:$u}')" >/dev/null
        echo "   updated  $name"
      else
        id="$(curl -sS -X POST "$BS_WH" -H "Authorization: Bearer $BETTERSTACK_API_TOKEN" \
          -H 'Content-Type: application/json' -d "$attrs" | jq -r '.data.id')"
        [ -n "$id" ] && [ "$id" != null ] || die "could not create webhook $name"
        echo "   created  $name"
      fi

      # The template MUST go in a request of its own. A PATCH that also carries
      # top-level fields returns 200 and silently discards it — which is how these
      # ended up with no body at all, i.e. alerting that looks configured and is not.
      tid="$(curl -sS "$BS_WH/$id" -H "Authorization: Bearer $BETTERSTACK_API_TOKEN" \
        | jq -r '.data.relationships.custom_webhook_template.data.id // empty')"
      curl -sS -X PATCH "$BS_WH/$id" -H "Authorization: Bearer $BETTERSTACK_API_TOKEN" \
        -H 'Content-Type: application/json' \
        -d "$(jq -nc --arg c "$chat" --arg t "$text" --arg tid "$tid" \
          '{custom_webhook_template_attributes:
             ((if $tid == "" then {} else {id:($tid|tonumber)} end)
              + {http_method:"post",
                 # Without this Telegram answers "message text is empty" and the
                 # alert is lost: it will not parse a body it was not told about.
                 headers_template:[{name:"Content-Type", value:"application/json"}],
                 body_template:({chat_id:$c, text:$t} | tostring)})}')" >/dev/null

      # Read back rather than trust the 200 — silent discard is the failure mode here.
      got="$(curl -sS "$BS_WH/$id?include=custom_webhook_template" \
        -H "Authorization: Bearer $BETTERSTACK_API_TOKEN")"
      jq -e --arg t "$text" '[.included[]? | select((.attributes.body_template // "") | contains($t))
             | select([.attributes.headers_template[]?.name] | index("Content-Type"))] | length > 0' \
        >/dev/null <<<"$got" \
        || die "$name did not save its body or Content-Type header — Telegram would reject every alert"
      # The bot token lives in the URL, so rotating it strands every webhook. Same
      # silent failure as the rest: Telegram just 404s and nobody is paged.
      jq -e --arg u "$url" '.data.attributes.url == $u' >/dev/null <<<"$got" \
        || die "$name did not save its url — the bot token in it is stale, so nothing is delivered"
    }
    upsert_webhook down "🔴 nabz: incident STARTED — https://uptime.betterstack.com" true false
    upsert_webhook up   "🟢 nabz: incident resolved" false true
    echo "   chat id $chat"
  fi
fi

echo "==> Better Stack heartbeat (evaluator dead-man's switch)"
# Unlike the outgoing webhooks, heartbeats are real per-environment resources, so
# staging and production each get their own. No server-side upsert here, so match
# on name the way the monitors match on url.
HB_NAME="nabz-evaluator (${ENV_NAME})"
hbs="$(curl -sS "$BS_HB" -H "Authorization: Bearer $BETTERSTACK_API_TOKEN")"
hb_id="$(jq -r --arg n "$HB_NAME" '.data[] | select(.attributes.name == $n) | .id' <<<"$hbs" | head -1)"
hb_body="$(jq -nc --arg n "$HB_NAME" '{name:$n, period:300, grace:300}')"
if [ -n "$hb_id" ]; then
  hb="$(curl -sS -X PATCH "$BS_HB/$hb_id" -H "Authorization: Bearer $BETTERSTACK_API_TOKEN" \
    -H 'Content-Type: application/json' -d "$hb_body")"
  echo "   updated  $HB_NAME"
else
  hb="$(curl -sS -X POST "$BS_HB" -H "Authorization: Bearer $BETTERSTACK_API_TOKEN" \
    -H 'Content-Type: application/json' -d "$hb_body")"
  echo "   created  $HB_NAME"
fi
PING_URL="$(jq -r '.data.attributes.url // empty' <<<"$hb")"
[ -n "$PING_URL" ] || die "Better Stack heartbeat: no url returned — $(jq -c '.' <<<"$hb")"
echo "   period 5m, grace 5m"
echo "   ping URL: $PING_URL"
echo "   (nothing to store — remote-deploy.sh reads it back from this same API)"

# A second heartbeat for the nightly PocketBase maintenance run (#322). A backup
# that silently stops is indistinguishable from no backup, and the run happens
# unattended on a host nobody watches — so it pings only on success and this
# alerts on silence, rather than relying on a failure notification that itself
# has to be delivered from the machine that just failed.
echo "==> Better Stack heartbeat (PocketBase maintenance)"
MHB_NAME="nabz-pb-maintenance (${ENV_NAME})"
mhb_id="$(jq -r --arg n "$MHB_NAME" '.data[] | select(.attributes.name == $n) | .id' <<<"$hbs" | head -1)"
# Daily, with a wide grace: one missed night is a hiccup, two is a real problem,
# and paging at 03:20 for a run that will succeed at 03:17 tomorrow is noise.
mhb_body="$(jq -nc --arg n "$MHB_NAME" '{name:$n, period:86400, grace:21600}')"
if [ -n "$mhb_id" ]; then
  mhb="$(curl -sS -X PATCH "$BS_HB/$mhb_id" -H "Authorization: Bearer $BETTERSTACK_API_TOKEN" \
    -H 'Content-Type: application/json' -d "$mhb_body")"
  echo "   updated  $MHB_NAME"
else
  mhb="$(curl -sS -X POST "$BS_HB" -H "Authorization: Bearer $BETTERSTACK_API_TOKEN" \
    -H 'Content-Type: application/json' -d "$mhb_body")"
  echo "   created  $MHB_NAME"
fi
MAINT_PING_URL="$(jq -r '.data.attributes.url // empty' <<<"$mhb")"
[ -n "$MAINT_PING_URL" ] || die "Better Stack maintenance heartbeat: no url returned"
echo "   period 24h, grace 6h"
echo "   ping URL: $MAINT_PING_URL"

echo
echo "Alerting is NOT fully configured here: Better Stack has no Telegram"
echo "integration, so the outgoing webhooks above are how alerts reach Telegram."
echo "Check On-call > Escalation policy covers the monitors and the heartbeat."
echo "Email is a poor choice — it can fail in the same way nabz does."
