// Adds a Cron Trigger handler to the built Cloudflare Worker (#339).
//
// Why a post-build step and not a hand-written entry file: adapter-cloudflare
// WRITES the worker to whatever `main` in wrangler.toml points at. Pointing
// `main` at a wrapper therefore makes the build overwrite the wrapper — silently,
// and the deployed Worker simply has no `scheduled` handler. (Found the hard way:
// wrangler still bundled and dry-ran clean, because the file it bundled was a
// perfectly valid worker. Just not ours.)
//
// So: let the adapter write where it wants, then rename it and put a wrapper in
// its place. Runs after every cloudflare build, so it cannot drift out of sync.

import { existsSync, readFileSync, renameSync, writeFileSync, appendFileSync } from 'node:fs';
import { join } from 'node:path';

const DIR = '.svelte-kit/cloudflare';
const ENTRY = join(DIR, '_worker.js');
const GENERATED = join(DIR, '_worker.generated.js');
const ASSETSIGNORE = join(DIR, '.assetsignore');

if (!existsSync(ENTRY)) {
	console.error(`wrap-worker: ${ENTRY} not found — did the cloudflare build run?`);
	process.exit(1);
}

// Idempotent: a second run must not wrap the wrapper.
if (readFileSync(ENTRY, 'utf8').includes('NABZ_CRON_WRAPPER')) {
	console.log('wrap-worker: already wrapped');
	process.exit(0);
}

renameSync(ENTRY, GENERATED);

writeFileSync(
	ENTRY,
	`// NABZ_CRON_WRAPPER — generated by scripts/wrap-worker.mjs. Do not edit.
import worker from './_worker.generated.js';

export default {
	fetch: worker.fetch,

	// Path-liveness beat. Deliberately goes through fetch() rather than talking to
	// PocketBase directly: the point is to prove the REAL check-in path works, so
	// it has to travel it — same route, same service account, same
	// Worker -> edge -> Access -> Tunnel -> PocketBase hops a customer's /ping
	// takes. A direct write from here would prove something easier and useless.
	async scheduled(event, env, ctx) {
		if (!env.HEALTH_DEBUG_TOKEN) return; // endpoint disabled; nothing to beat
		const base = (env.WEB_URL || 'https://nabz.sh').replace(/\\/$/, '');
		const req = new Request(base + '/internal/liveness', {
			method: 'POST',
			headers: { authorization: 'Bearer ' + env.HEALTH_DEBUG_TOKEN }
		});
		ctx.waitUntil(
			worker
				.fetch(req, env, ctx)
				.then((res) => {
					// Loud on purpose: silence here makes the evaluator hold heartbeat
					// verdicts, and the reason for that needs to be findable.
					if (!res.ok) console.error('liveness beat failed: ' + res.status);
				})
				.catch((e) => console.error('liveness beat threw: ' + e))
		);
	}
};
`
);

// The renamed file sits in the assets directory, so without this it would be
// served publicly — the whole server bundle, downloadable.
const ignore = existsSync(ASSETSIGNORE) ? readFileSync(ASSETSIGNORE, 'utf8') : '';
if (!ignore.split('\n').includes('_worker.generated.js')) {
	appendFileSync(
		ASSETSIGNORE,
		(ignore.endsWith('\n') || !ignore ? '' : '\n') + '_worker.generated.js\n'
	);
}

console.log('wrap-worker: added scheduled handler');
